<a href="https://colab.research.google.com/github/Alberta0/Purchase-Prediction/blob/main/Customer_behaviour_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

##Import necessary libraries

In [3]:
import pandas as pd
import numpy as np

##Importing dataset

In [4]:
df = pd.read_csv('/content/drive/MyDrive/ecommerce_customer_data.csv')

##Exploring dataset.


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype  
---  ------                 --------------   -----  
 0   Customer ID            250000 non-null  int64  
 1   Purchase Date          250000 non-null  object 
 2   Product Category       250000 non-null  object 
 3   Product Price          250000 non-null  int64  
 4   Quantity               250000 non-null  int64  
 5   Total Purchase Amount  250000 non-null  int64  
 6   Payment Method         250000 non-null  object 
 7   Customer Age           250000 non-null  int64  
 8   Returns                202404 non-null  float64
 9   Customer Name          250000 non-null  object 
 10  Age                    250000 non-null  int64  
 11  Gender                 250000 non-null  object 
 12  Customer Cancellation  250000 non-null  int64  
dtypes: float64(1), int64(7), object(5)
memory usage: 24.8+ MB


In [6]:
#check for missing values
df.isnull().sum()

Customer ID                  0
Purchase Date                0
Product Category             0
Product Price                0
Quantity                     0
Total Purchase Amount        0
Payment Method               0
Customer Age                 0
Returns                  47596
Customer Name                0
Age                          0
Gender                       0
Customer Cancellation        0
dtype: int64

In [8]:
value=0
df['Returns'].fillna(value, inplace=True)

<ipython-input-8-9204d37caa30>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Returns'].fillna(value, inplace=True)


In [9]:
df.isnull().sum()

Customer ID              0
Purchase Date            0
Product Category         0
Product Price            0
Quantity                 0
Total Purchase Amount    0
Payment Method           0
Customer Age             0
Returns                  0
Customer Name            0
Age                      0
Gender                   0
Customer Cancellation    0
dtype: int64

In [10]:
#converting categorical variable to numerical variables
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

ls = ['Purchase Date','Product Category','Payment Method','Customer Name','Gender']

for col in ls:
  df[col] = le.fit_transform(df[col])

In [11]:
#Selecting Target Variable
X = df.drop(columns='Customer Cancellation')
y = df['Customer Cancellation']

In [12]:
#splitting dataset to train and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 42)

Implementing models

In [13]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

In [14]:
def LR(X_train, X_test, y_train, y_test):
  logReg = LogisticRegression()
  logReg.fit(X_train, y_train)
  y_pred = logReg.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [15]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

In [16]:
def rfc(X_train, X_test, y_train, y_test):
  random_for = RandomForestClassifier()
  random_for.fit(X_train, y_train)
  y_pred = random_for.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [17]:
#Adaptive Boosting or AdaBoost
from sklearn.ensemble import AdaBoostClassifier

In [18]:
def AdaB(X_train, X_test, y_train, y_test):
  ada_boost = AdaBoostClassifier()
  ada_boost.fit(X_train, y_train)
  y_pred = ada_boost.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [19]:
#XGB Classifier
from xgboost.sklearn import XGBClassifier

In [20]:
def xgb(X_train, X_test, y_train, y_test):
  xgboost = XGBClassifier()
  xgboost.fit(X_train, y_train)
  y_pred = xgboost.predict(X_test)

  print(confusion_matrix(y_test, y_pred))
  print(classification_report(y_test, y_pred))

In [21]:
LR(X_train, X_test, y_train, y_test)

[[50035     0]
 [12465     0]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89     50035
           1       0.00      0.00      0.00     12465

    accuracy                           0.80     62500
   macro avg       0.40      0.50      0.44     62500
weighted avg       0.64      0.80      0.71     62500



/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no pre

In [22]:
rfc(X_train, X_test, y_train, y_test)

[[50029     6]
 [12370    95]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89     50035
           1       0.94      0.01      0.02     12465

    accuracy                           0.80     62500
   macro avg       0.87      0.50      0.45     62500
weighted avg       0.83      0.80      0.72     62500



In [23]:
AdaB(X_train, X_test, y_train, y_test)

[[50035     0]
 [12465     0]]
              precision    recall  f1-score   support

           0       0.80      1.00      0.89     50035
           1       0.00      0.00      0.00     12465

    accuracy                           0.80     62500
   macro avg       0.40      0.50      0.44     62500
weighted avg       0.64      0.80      0.71     62500



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [24]:
xgb(X_train, X_test, y_train, y_test)

[[49955    80]
 [12023   442]]
              precision    recall  f1-score   support

           0       0.81      1.00      0.89     50035
           1       0.85      0.04      0.07     12465

    accuracy                           0.81     62500
   macro avg       0.83      0.52      0.48     62500
weighted avg       0.81      0.81      0.73     62500



###Finetuning the Models for better accuracy and performance using GridSearchCV

In [25]:
from sklearn.model_selection import GridSearchCV

# For Logistic Regression
log_reg = LogisticRegression()

# Defining the parameter grid
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'penalty': ['l1', 'l2']
}

In [26]:
# Create GridSearchCV
grid_search = GridSearchCV(estimator=log_reg, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2']},
             scoring='accuracy')

In [27]:
# Best parameters and best score
print("Best parameters:", grid_search.best_params_)
print("Accuracy score:", grid_search.best_score_)

Best parameters: {'C': 0.001, 'penalty': 'l2'}
Accuracy score: 0.8004853333333333


In [28]:
# For Random Forest Classifier
random_forest = RandomForestClassifier()

# Defining  the parameter grid
param_grid = {
    'n_estimators': [5,7,12],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [100, 200, 300, 400, 500]
}


In [29]:
grid_search = GridSearchCV(estimator=random_forest, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning: 
75 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 1382, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.11/dist-packages/sklearn/base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [100, 200, 300, 400, 500],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [5, 7, 12]},
             scoring='accuracy')

In [30]:
# Best parameters and best score
print("Best parameters:", grid_search.best_params_)
print("Accuracy score:", grid_search.best_score_)

Best parameters: {'max_depth': 100, 'max_features': 'log2', 'n_estimators': 12}
Accuracy score: 0.79992


In [31]:
# For Adaptive Boosting
ada_boost = AdaBoostClassifier()

# Define the parameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.1, 0.1, 1, 10]
}

In [32]:
grid_search = GridSearchCV(estimator=ada_boost, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.1, 0.1, 1, 10],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [33]:
# Best parameters and best score
print("Best parameters:", grid_search.best_params_)
print("Accuracy score:", grid_search.best_score_)

Best parameters: {'learning_rate': 0.1, 'n_estimators': 50}
Accuracy score: 0.8004853333333333


In [39]:
from xgboost import XGBClassifier

# Define the model
xgb = XGBClassifier()

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300, 400, 500],
    'learning_rate': [0.01, 0.1, 1, 10],
    'max_depth': [100, 200, 300, 400, 500]
}

In [ ]:
grid_search = GridSearchCV(estimator=xgb, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

In [ ]:
# Best parameters and Accuracy score
print("Best parameters:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)